baseURL       = "http://melaniesinclair.xyz/"
languageCode  = "en-us"
title         = "Melanie Sinclair's UX Design Portfolio"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 1
  [[menu.nav]]
    name    = "Portfolio"
    url     = ""
    weight  = 2
  [[menu.nav]]
    name    = "Resume"
    url     = "resume"
    weight  = 3

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Melanie Sinclair's UX Design Portfolio"
  author = "Melanie Sinclair"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/f/xknyrygv"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Portfolio"
    url     = "portfolio"
  

  # Banner Section
  [params.banner]
    enable                = false
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Melanie Sinclair, UX Designer"
    tagline               = "ignore"
    primary_button        = "See My Works"
    primary_button_url    = "portfolio"
    secondary_button      = "View Resume"
    secondary_button_url  = "resume"

  [params.portfolio]
    enable    = true
    title     = "Melanie Sinclair,"
	subtitle = "UX Designer"
    description  = "Site currently under construction!"

  [params.footer]
      # Footer Contact Info
      [params.footer.contactInfo]
        title   = "Contact"
        email   = "hello@melaniesinclair.xyz"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "LinkedIn"
          url  = "https://www.linkedin.com/in/melanie-sinclair/"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "https://dribbble.com/Aviakio"