baseURL       = "http://melaniesinclair.xyz/"
languageCode  = "en-us"
title         = "Melanie Sinclair's UX Design Portfolio"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 1
  [[menu.nav]]
    name    = "Resume"
    url     = "resume"
    weight  = 2

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Melanie Sinclair - UX Design Portfolio"
  author = "Melanie Sinclair"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Portfolio"
    url     = "portfolio"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.png"
    heading               = ""
    tagline               = ""

  [params.portfolio]
    enable    = true
    title     = "Melanie Sinclair"
	subtitle = "UI/UX Designer"
    description  = "Site is currently under construction. Please come back later for my design projects!"

  [params.footer]
      # Footer Contact Info
      [params.footer.contactInfo]
        title   = "Contact"
        email   = "hello@melaniesinclair.xyz"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "LinkedIn"
          url  = "https://www.linkedin.com/in/melanie-sinclair/"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "https://dribbble.com/Aviakio"